name: "fastapi-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "fastapi-app"
setup.template.pattern: "fastapi-app-*"

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /src/logs/fastapi-efk.log
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "fastapi-app-%{[agent.version]}"

logging.level: info
